import { NextComponentType } from 'next';
import { BaseContext } from 'next/dist/shared/lib/utils';
import Head from 'next/head';
import React from 'react';

type Props = React.DetailedHTMLProps<
  React.HTMLAttributes<HTMLElement>,
  HTMLElement
> & { title?: string };

export const Page: NextComponentType<BaseContext, unknown, Props> = ({
  title = 'try it on ai',
  ...props
}) => {
  return (
    <React.Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main {...props} />
    </React.Fragment>
  );
};
